---
# tasks file for aws-get

#========================= GATHER VPC INFO ==================== TAG: always =======================
- name: get VPC info
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_tag_name }}"
    region: "{{ user_region }}"
  register: vpcs
  tags: always

- name: display vpc-id
  debug: 
    var: vpcs.vpcs[0].id
  tags: always

#====================== GATHER SUBNET INFO ===================== TAG: always ======================
- name: get subnet info
  ec2_vpc_subnet_info:
    filters: 
      "tag:Name": "{{ sub_tag_name }}"
      vpc-id: "{{ vpcs.vpcs[0].id }}"
    region: "{{ user_region }}"
  register: aws_subnets
  tags: always
- debug: 
    var: aws_subnets.subnets[0].id
  tags: always  

#====================== GATHER SEC GROUP INFO ================= TAG: always =====================
- name: get secuirty group info
  ec2_group_info: 
    filters:
      "tag:Name": "{{ sec_tag_name }}"
      vpc-id: "{{ vpcs.vpcs[0].id }}" 
    region: "{{ user_region }}"
  register: aws_groups
  tags: always
- debug: 
    var: aws_groups.security_groups[0].group_id
  tags: always

