---
# tasks file for aws-get

#========================= GATHER VPC INFO ==================== 
- name: get VPC info
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_tag_name }}"
    region: "{{ user_region }}"
  register: vpcs
  tags: 
    - gather-ec2-info
    - create-ec2

- name: display vpc-id
  debug: 
    var: vpcs.vpcs[0].id
  tags: 
    - gather-ec2-info
    - create-ec2
    
#====================== GATHER SUBNET INFO ===================== 
- name: get subnet info
  ec2_vpc_subnet_info:
    filters: 
      "tag:Name": "{{ sub_tag_name }}"
      vpc-id: "{{ vpcs.vpcs[0].id }}"
    region: "{{ user_region }}"
  register: aws_subnets
  tags: 
    - gather-ec2-info
    - create-ec2
- debug: 
    var: aws_subnets.subnets[0].id
  tags: 
    - gather-ec2-info
    - create-ec2  

#====================== GATHER SEC GROUP INFO ================= 
- name: get secuirty group info
  ec2_group_info: 
    filters:
      "tag:Name": "{{ sec_tag_name }}"
      vpc-id: "{{ vpcs.vpcs[0].id }}" 
    region: "{{ user_region }}"
  register: aws_groups
  tags: 
    - gather-ec2-info
    - create-ec2
- debug: 
    var: aws_groups.security_groups[0].group_id
  tags: 
    - gather-ec2-info
    - create-ec2

#====================== VALIDATE EC2 INFO ======================
- name: validate ec2 has been created
  command: "python3.8 ./validate_ec2_creation.py {{ user_region }} {{ sec_tag_name }}"
  args:
    chdir: "{{ role_path }}/files"
  run_once: true
  tags:
    - validate-ec2
  register: out
- debug:
    var: out
  tags:
    - validate-ec2