---
# tasks file for aws-post
#===================== CREATE OPENLDAP EC2 INSTANCE =========== TAG: create-ec2 =======================
- name: EC2 instance
  ec2_instance:
    name: "{{ ec2_name }}" 
    vpc_subnet_id: "{{ aws_subnets.subnets[0].id }}"
    instance_type: "{{ ec2_instance_type }}"
    security_group: "{{ aws_groups.security_groups[0].group_id }}"
    key_name: "{{ ec2_key_name }}"
    image_id: "{{ ec2_image_id }}"
    region: "{{ ec2_region }}"
    network:
      assign_public_ip: true 
  tags: create-ec2

#====================== VALIDATE EC2 INFO ======================
- name: validate ec2 has been created
  command: "python3.8 ./validate_ec2_creation.py {{ ec2_region }} {{ ec2_name }}"
  args:
    chdir: "{{ role_path }}/files"
  run_once: true
  tags:
    - validate-ec2
    - create-ec2
  register: out
- debug:
    var: out.stdout
  tags:
    - validate-ec2
    - create-ec2