---
# tasks file for aws-post
#===================== CREATE OPENLDAP EC2 INSTANCE =========== TAG: create-ec2 =======================
    - name: EC2 instance
      ec2_instance:
        name: "{{ ec2_name }}" 
        vpc_subnet_id: "{{ aws_subnets.subnets[0].id }}"
        instance_type: "{{ ec2_instance_type }}"
        security_group: "{{ aws_groups.security_groups[0].group_id }}"
        key_name: "{{ ec2_key_name }}"
        image_id: "{{ ec2_image_id }}"
        region: "{{ ec2_region }}"
        network:
          assign_public_ip: true 
      tags: create-ec2
