---
- name: create and run ec2 instance
  hosts: localhost
  connection: local
  vars: 
    ansible_python_interpreter: /usr/bin/python3.8
  gather_facts: no
  tasks:
#========================= GATHER VPC INFO ==================== TAG: always =======================
    - name: get VPC infos
      ec2_vpc_net_info:
        filters:
          "tag:Name": ANS0905-AUTO #TEMPLATE
        region: us-east-1 #TEMPLATE
      register: vpcs
      tags: always

    - name: display vpc-id
      debug: 
        var: vpcs
      tags: always

#====================== GATHER SUBNET INFO ===================== TAG: always ======================
    - name: get subnet info
      ec2_vpc_subnet_info:
        filters: 
          "tag:Name": ANS0905-SUBNET #TEMPLATE
          vpc-id: "{{ vpcs.vpcs[0].id }}"
        region: us-east-1 #TEMPLATE
      register: aws_subnets
      tags: always
    - debug: 
        var: aws_subnets.subnets[0].id
      tags: always  

#====================== GATHER SEC GROUP INFO ================= TAG: always =====================
    - name: get secuirty group info
      ec2_group_info: 
        filters:
          "tag:Name": ANS0905-SECGRP #TEMPLATE
          vpc-id: "{{ vpcs.vpcs[0].id }}" 
        region: us-east-1 #TEMPLATE
      register: aws_groups
      tags: always
    - debug: 
        var: aws_groups.security_groups[0].group_id
      tags: always
#===================== CREATE OPENLDAP EC2 INSTANCE =========== TAG: oldap =======================
    - name: EC2 instance
      ec2_instance:
        name: LDAP0905_TEST #TEMPLATE
        vpc_subnet_id: "{{ aws_subnets.subnets[0].id }}"
        instance_type: t2.micro #TEMPLATE
        security_group: "{{ aws_groups.security_groups[0].group_id }}"
        key_name: OpenLabEC2Key #TEMPLATE
        image_id: ami-029c0fbe456d58bd1 #TEMPLATE
        region: us-east-1 #TEMPLATE
        network:
          assign_public_ip: true 
      tags: oldap

#=================== GATHER EC2 INFO ========================= TAG: ec2-info ================
#    - name: get ec2 info
      
