---
- name: create and run ec2 instance
  hosts: localhost
  connection: local
  vars: 
    ansible_python_interpreter: /usr/bin/python3.8
  gather_facts: no
  roles:
    - aws-get
  tasks:

#=================== GATHER EC2 INFO ========================= TAG: ec2-info ================
#    - name: get ec2 info
      
