---
- name: create and run ec2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - aws-post

  post_tasks:
#====================== VALIDATE EC2 INFO ======================
  - name: validate ec2 has been created
    command: "python3.8 ./validate_ec2_creation.py {{ ec2_region }} {{ ec2_name }}"
    args:
      chdir: "{{ role_path }}/files"
    run_once: true
    tags:
      - validate-ec2
    register: out
  - debug:
      var: out.stdout
    tags:
      - validate-ec2
      - create-ec2
      
