---
- name: loop example
  hosts: openldap
  vars: 
    env: staging
  become: true

  tasks:
#======================================================================================
# MISSY ELLIOT ===================== MISSY ELLIOT ======================== MISSY ELLIOT
# =====================================================================================
#
#================== LOOP EXAMPLE ==================== TAG: loop_csv ===================
    - name: read csv
      read_csv:
        path: /root/hosts.csv #path on Remote
        key: hostname         #first header
      register: vms           #global var
      tags: loop_csv
    - debug:
        msg: "{{ item.key }}:
              {{ item.value.hostname }},
              {{ item.value.partition }},
              {{ item.value.ip }}"
      loop: "{{ vms.dict|dict2items }}"
      tags: loop_csv

#================= TEMPLATE EXAMPLE =============== TAG: template ====================
    - name: Config file onto remote host
      template:
        src: ../templates/app.conf.j2 #path on ans_host
        dest: /etc/my_app.conf        #path on remote
      tags: template

#================= SIMPLE COMMAND EXAMPLE ========= TAG: whoami ===================== 
    - name: add user to ldap
      command: whoami   
      register: myout #command output
      tags: whoami

    - debug:
        var: myout.stdout_lines
      tags: whoami
 
#================ SIMPLE INSTALL EXAMPLE ========= TAG: install ======================
    - name: install dos2unix
      yum:
        name:  dos2unix
        state: latest
      tags: install




#==================================================================================================================
# AWS EXAMPLES ================================= AWS EXAMPLES ======================================== AWS EXAMPLES
#==================================================================================================================
#
#=============== Gather Info for EC2 Instance ===============================
#=============== VPC INFO ======================================================== TAG: get-vpc-info ==============
    - name: get VPC info
      ec2_vpc_net_info:
        filters:
          "tag:Name": ANS0905-AUTO TEMPLATE
        region: us-east-1 TEMPLATE
      register: vpcs
      tags: get-vpc-info

    - name: display vpc-id
      debug:
        var: vpcs.vpcs[0].id
      tags: get-vpc-info

#============= SUBNET INFO ====================================================== TAG: get-subnet-info ============
    - name: get subnet info
      ec2_vpc_subnet_info:
        filters:
          "tag:Name": ANS0905-SUBNET TEMPLATE
          vpc-id: "{{ vpcs.vpcs[0].id }}"
        region: us-east-1 TEMPLATE
      register: aws_subnets
      tags: get-subnet-info
    - debug:
        var: aws_subnets.subnets[0].id
      tags: get-subnet-info

#============ SECURITY GROUP INFO  =============================================== TAG: get-secgroup-info ==========
    - name: get secuirty group info
      ec2_group_info:
        filters:
          "tag:Name": ANS0905-SECGRP TEMPLATE
          vpc-id: "{{ vpcs.vpcs[0].id }}"
        region: us-east-1 TEMPLATE
      register: aws_groups
      tags: get-secgroup-info
    - debug:
        var: aws_groups.security_groups[0].group_id
      tags: get-secgroup-info

#=========== CREATE AWS EC2 ================================================
    - name: EC2 instance
      ec2_instance:
        name: LDAP0905_TEST #TEMPLATE
        vpc_subnet_id: "{{ aws_subnets.subnets[0].id }}"
        instance_type: t2.micro #TEMPLATE
        security_group: "{{ aws_groups.security_groups[0].group_id }}"
        key_name: OpenLabEC2Key #TEMPLATE
        image_id: ami-029c0fbe456d58bd1 #TEMPLATE
        region: us-east-1 #TEMPLATE
        network:
          assign_public_ip: true
      tags: OLDAP
