
- hosts: openldap
  become: true
  tasks:
    - name: read csv
      read_csv:
        path: /root/hosts.csv
        key: hostname
      register: vms
    - debug:
        msg: "{{ item.key }}:
              {{ item.value.hostname }},
              {{ item.value.partition }},
              {{ item.value.ip }}"
      loop: "{{ vms.dict|dict2items }}"
