---
#Playbook for all OpenLDAP processes
- name: OpenLDAP Playbook
  hosts: openldap
  become: true
  vars:
    ldap_auth:
      server_uri: ldap://localhost/
      bind_dn: cn=service,dc=doed,dc=fsa,dc=com
      bind_pw: "servicepassword"
  
#==================== READ FROM CSV ====================================               ===================
  tasks:
  - name: Read users from CSV file
    read_csv:
      path: "~/users.csv"
      key: name
    register: users
    tags:
      - addusers
      - removeusers

#==================== ADD USER ENTRY FOR USERS IN CSV ================== TAG: addusers ===================
  - name: add user entry
    ldap_entry:
      dn: "uid={{ item.value.name }},ou=Users,dc=doed,dc=fsa,dc=com"
      objectClass:
        - top
        - account
        - posixAccount
        - shadowAccount
      attributes:
        cn: "{{ item.value.name }}"      
        uid: "{{ item.value.name }}"
        gidNumber: 0
        uidNumber: "{{ item.value.uidNumber }}"
        homeDirectory: "/home/{{ item.value.name }}"
        userPassword: "{SSHA}wvg4XzCC3vOZAUyA8bPQnOhkfaz50FyD"
        loginShell: /bin/bash
        gecos: "{{ item.value.name }}"
        shadowLastChange: 0
        shadowMax: 0
        shadowWarning: 0
    args: "{{ ldap_auth }}"
    loop: "{{ users.dict|dict2items }}"
    tags:  addusers
   
#================== REMOVE ENTRY FOR USERS IN CSV ========================= TAG: removeusers ============
  - name: remove user entry 
    ldap_entry:
      dn: "uid={{ item.value.name }},ou=Users,dc=doed,dc=fsa,dc=com"
      state: absent
    args: "{{ ldap_auth }}"
    loop: "{{ users.dict|dict2items }}"
    tags: removeusers

#================= ADD OU GROUP ========================================= TAG: add group ===============
  - name: create group in parent ou 'Groups'
    ldap_entry:
      dn: "ou=Tableau/Serverless Ops,ou=Groups,dc=doed,dc=fsa,dc=com"
      



