---
#Playbook for all OpenLDAP processes
- name: OpenLDAP Playbook
  hosts: openldap
  become: true
  vars:
    ldap_auth:
      server_uri: ldap://localhost/
      bind_dn: cn=service,dc=doed,dc=fsa,dc=com
      bind_pw: "servicepassword"
  
  tasks:
  - name: Read users from CSV file
    read_csv:
      path: "~/users.csv"
      key: name
    register: users
    tags:
      - adduser
      - removeuser
      - loop

  - debug:
      msg: "User {{ item.value.name }} has UID {{ item.value.name }} and GID {{ item.value.gidNumber }}"
    loop: "{{ user.dict|dict2items }}"
    tags: 
      - loop

  - name: add user entry
    ldap_entry:
      dn: "uid={{ item }},ou=Users,dc=doed,dc=fsa,dc=com"
      objectClass:
        - top
        - account
        - posixAccount
        - shadowAccount
      attributes:      
        cn: "{{ item }}"
        uid: "{{ item }}"
        gidNumber: 0
        uidNumber: 1009
        homeDirectory: "/home/{{ item }}"
        userPassword: "{SSHA}wvg4XzCC3vOZAUyA8bPQnOhkfaz50FyD"
        loginShell: /bin/bash
        gecos: "{{ item }}"
        shadowLastChange: 0
        shadowMax: 0
        shadowWarning: 0
    args: "{{ ldap_auth }}"
    tags:
      - adduser
    loop: "{{ lookup('dict', users) }}"

  - name: remove user entry 
    ldap_entry:
      dn: "uid={{ item }},ou=Users,dc=doed,dc=fsa,dc=com"
      state: absent
    args: "{{ ldap_auth }}"
    tags:
      - removeuser
