---
# tasks file for aws-ec2-openldap

#========================= GATHER VPC INFO ==================== TAG: always =======================
- name: get VPC info
  ec2_vpc_net_info:
    filters:
      "tag:Name": ANS0905-AUTO #TEMPLATE
    region: us-east-1 #TEMPLATE
  register: vpcs
  tags: always

- name: display vpc-id
  debug: 
    var: vpcs
  tags: always

